version: '2.1'

services:

  guacd:
    image: guacamole/guacd:${GUACAMOLE_VERSION}
    restart: unless-stopped
    volumes:
      - ./drive:/drive
    network_mode: "service:guacamole"

  mysql:
    build:
      context: ./build-mysql
      args:
        GUACAMOLE_VERSION: ${GUACAMOLE_VERSION}
        MYSQL_VERSION: ${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    network_mode: "service:guacamole"


  guacamole:
    image: guacamole/guacamole:${GUACAMOLE_VERSION}
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: localhost
      MYSQL_HOSTNAME: localhost
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      REMOTE_IP_VALVE_ENABLED: true
    labels:
      - traefik.enable=true
      - traefik.http.services.guacamole.loadbalancer.server.port=8080 # Container port
      - traefik.http.routers.guacamole.rule=Host(`${DOMAIN}`) # URL
      - traefik.http.routers.guacamole.tls.certresolver=letsencrypt # Cert resolver declared as traefik flag
      - traefik.http.routers.guacamole.entrypoints=https # Incoming entrypoint
      - traefik.http.routers.guacamole.middlewares=authelia@docker

networks:
  default:
    name: traefik-proxy
volumes:
  dbdata:
